# Generated by Django 5.2.17 on 2026-09-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='resolve',
            new_name='role',
        ),
    ]
